# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fing < Formula
  desc ""
  homepage "https://fing.ir"
  version "0.2.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fingcloud/cli/releases/download/v0.2.3/fing-darwin-arm64.tar.gz"
      sha256 "b64498184af54c62e113ab886e8446b1eb7b49b7b54a3c24d15b2b4fd2f48ca5"

      def install
        bin.install "fing"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fingcloud/cli/releases/download/v0.2.3/fing-darwin-amd64.tar.gz"
      sha256 "00a02f58e4443c1040e96d83da4f0c84509d9b9c26887ab25aa8f789a56dc25d"

      def install
        bin.install "fing"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/fingcloud/cli/releases/download/v0.2.3/fing-linux-amd64.tar.gz"
      sha256 "e2dd364c8f51c49c9b0cea3fc1d6bf4493d833aec20492cb1082eb1f7d22311d"

      def install
        bin.install "fing"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fingcloud/cli/releases/download/v0.2.3/fing-linux-arm64.tar.gz"
      sha256 "04502e8364fa878e8708538a8eb499e08f100cd2e4092264c327408eff446dbe"

      def install
        bin.install "fing"
      end
    end
  end

  test do
    system "#{bin}/fing version"
  end
end
