# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fing < Formula
  desc ""
  homepage "https://fing.ir"
  version "0.1.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fingcloud/cli/releases/download/v0.1.3/fing-0.1.3-darwin-amd64.tar.gz"
      sha256 "f0391a2aa6532884f2abdb5b5865f2ecba47f519c41a4827ed434a5602b03a62"
    end
    if Hardware::CPU.arm?
      url "https://github.com/fingcloud/cli/releases/download/v0.1.3/fing-0.1.3-darwin-arm64.tar.gz"
      sha256 "4c44537dd00b5bee999522f5d857681fe7e298967f99d25ae8cf48f0a537d793"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/fingcloud/cli/releases/download/v0.1.3/fing-0.1.3-linux-amd64.tar.gz"
      sha256 "f1b8f749721f79d5a7e4b6bddd4806522025e2e3e2406d5b9b732634d833a69f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fingcloud/cli/releases/download/v0.1.3/fing-0.1.3-linux-arm64.tar.gz"
      sha256 "6bfbc5873f59b5f7e9c15e7ab654d2024af29d75ef8e6bbe2da8572e962978fc"
    end
  end

  def install
    bin.install "fing"
  end

  test do
    system "#{bin}/fing version"
  end
end
